-- Generated by matugen. Do not edit.
return {
	bg = "#101417",
	surface = "#101417",
	surface_container = "#1f2225",
	fg = "#e1e2e7",
	muted = "#c0c7d0",
	primary = "#b4ddff",
	on_primary = "#00344e",
	primary_container = "#80c3f5",
	secondary = "#b1c9df",
	tertiary = "#ffd096",
	error = "#ffb4ab",
	outline = "#8a9199",
}
