-- Generated by matugen. Do not edit.
local M = {}

local c = {
  bg = "#1b110f",
  surface = "#1b110f",
  surface_container = "#2a1f1d",
  fg = "#f2deda",
  muted = "#ddc0ba",
  primary = "#ffb4a5",
  on_primary = "#5e0d02",
  primary_container = "#e16f59",
  secondary = "#fab6a8",
  tertiary = "#6dd9c4",
  error = "#ffb4ab",
  outline = "#a58b86",
}

function M.setup()
  vim.opt.termguicolors = true
  vim.g.colors_name = "matugen-wallpaper"

  local hl = vim.api.nvim_set_hl
  hl(0, "Normal", { fg = c.fg, bg = "NONE" })
  hl(0, "NormalNC", { fg = c.fg, bg = "NONE" })
  hl(0, "NormalFloat", { fg = c.fg, bg = c.surface })
  hl(0, "FloatBorder", { fg = c.primary, bg = c.surface })
  hl(0, "Cursor", { fg = c.bg, bg = c.primary })
  hl(0, "Visual", { bg = c.primary_container })
  hl(0, "Search", { fg = c.on_primary, bg = c.primary })
  hl(0, "IncSearch", { fg = c.bg, bg = c.tertiary })
  hl(0, "LineNr", { fg = c.outline })
  hl(0, "CursorLineNr", { fg = c.primary, bold = true })
  hl(0, "CursorLine", { bg = c.surface_container })
  hl(0, "SignColumn", { bg = "NONE" })
  hl(0, "StatusLine", { fg = c.fg, bg = c.surface_container })
  hl(0, "StatusLineNC", { fg = c.muted, bg = c.surface })
  hl(0, "WinBar", { fg = c.fg, bg = c.surface_container, bold = true })
  hl(0, "WinBarNC", { fg = c.muted, bg = c.surface })
  hl(0, "WinSeparator", { fg = c.outline })
  hl(0, "EndOfBuffer", { fg = c.outline, bg = "NONE" })
  hl(0, "FoldColumn", { fg = c.muted, bg = "NONE" })
  hl(0, "LineNr", { fg = c.outline, bg = "NONE" })
  hl(0, "CursorLineNr", { fg = c.primary, bg = "NONE", bold = true })
  hl(0, "Pmenu", { fg = c.fg, bg = c.surface })
  hl(0, "PmenuSel", { fg = c.on_primary, bg = c.primary })
  hl(0, "Comment", { fg = c.muted, italic = true })
  hl(0, "String", { fg = c.secondary })
  hl(0, "Function", { fg = c.primary })
  hl(0, "Identifier", { fg = c.fg })
  hl(0, "Statement", { fg = c.tertiary })
  hl(0, "Keyword", { fg = c.tertiary, italic = true })
  hl(0, "Type", { fg = c.secondary })
  hl(0, "Constant", { fg = c.primary })
  hl(0, "Error", { fg = c.error })
  hl(0, "DiagnosticError", { fg = c.error })
  hl(0, "DiagnosticWarn", { fg = c.tertiary })
  hl(0, "DiagnosticInfo", { fg = c.primary })
  hl(0, "DiagnosticHint", { fg = c.secondary })

  -- lualine/winbar: force readable contrast after wallpaper theme changes.
  local lualine_groups = {
    lualine_a_normal = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_b_normal = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_c_normal = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_x_normal = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_y_normal = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_z_normal = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_a_insert = { fg = c.bg, bg = c.secondary, bold = true },
    lualine_b_insert = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_c_insert = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_x_insert = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_y_insert = { fg = c.bg, bg = c.secondary, bold = true },
    lualine_z_insert = { fg = c.bg, bg = c.secondary, bold = true },
    lualine_a_visual = { fg = c.bg, bg = c.tertiary, bold = true },
    lualine_b_visual = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_c_visual = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_x_visual = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_y_visual = { fg = c.bg, bg = c.tertiary, bold = true },
    lualine_z_visual = { fg = c.bg, bg = c.tertiary, bold = true },
    lualine_a_command = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_b_command = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_c_command = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_x_command = { fg = c.fg, bg = c.surface_container, bold = true },
    lualine_y_command = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_z_command = { fg = c.on_primary, bg = c.primary, bold = true },
    lualine_a_inactive = { fg = c.muted, bg = c.surface },
    lualine_b_inactive = { fg = c.muted, bg = c.surface },
    lualine_c_inactive = { fg = c.muted, bg = c.surface },
    lualine_x_inactive = { fg = c.muted, bg = c.surface },
    lualine_y_inactive = { fg = c.muted, bg = c.surface },
    lualine_z_inactive = { fg = c.muted, bg = c.surface },
  }
  for group, spec in pairs(lualine_groups) do
    hl(0, group, spec)
  end

  -- scheme-expressive semantic terminal colors
  vim.g.terminal_color_0 = c.surface
  vim.g.terminal_color_1 = c.error
  vim.g.terminal_color_2 = c.tertiary
  vim.g.terminal_color_3 = c.secondary
  vim.g.terminal_color_4 = c.primary
  vim.g.terminal_color_5 = c.inverse_primary
  vim.g.terminal_color_6 = c.tertiary_container
  vim.g.terminal_color_7 = c.fg
  vim.g.terminal_color_8 = c.surface_container
  vim.g.terminal_color_9 = c.error_container
  vim.g.terminal_color_10 = c.tertiary_fixed
  vim.g.terminal_color_11 = c.secondary_container
  vim.g.terminal_color_12 = c.primary_fixed
  vim.g.terminal_color_13 = c.primary_container
  vim.g.terminal_color_14 = c.secondary_fixed
  vim.g.terminal_color_15 = c.bg
end

return M
