-- Generated by matugen. Do not edit.
return {
	bg = "#1b110f",
	surface = "#1b110f",
	surface_container = "#2a1f1d",
	fg = "#f2deda",
	muted = "#ddc0ba",
	primary = "#ffb4a5",
	on_primary = "#5e0d02",
	primary_container = "#e16f59",
	secondary = "#fab6a8",
	tertiary = "#6dd9c4",
	error = "#ffb4ab",
	outline = "#a58b86",
}
