-- Generated by matugen. Do not edit.
return {
	bg = "#141316",
	surface = "#141316",
	surface_container = "#232124",
	fg = "#e7e1e5",
	muted = "#ccc4ce",
	primary = "#d5bdee",
	on_primary = "#37254d",
	primary_container = "#614d78",
	secondary = "#cec2d8",
	tertiary = "#caca85",
	error = "#ffb4ab",
	outline = "#958e98",
}
